# This workflow will do a clean install of node dependencies,
# run the linter to check for issues and the build the source code as a test.

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
    - run: npm ci
    - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
